repos:
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.11
        stages: [commit]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: poetry run pytest
        always_run: true
        pass_filenames: false
        stages: [commit]